#!/bin/bash
DAT=$(find . -mindepth 2 -maxdepth 2 -type d | grep -E '^./[[:digit:]]+/')
MAX_DAY=$(echo "$DAT" | cut -d'/' -f2 | sort -nr | head -n1)
LANGS=$(echo "$DAT" | cut -d'/' -f3 | sort | uniq)
LONGEST_LANG=$(echo "$LANGS" | awk '{print length}' | sort -nr | head -n1)

printf "%-${LONGEST_LANG}s " ""
echo -n "| "
echo -n `seq 1 $MAX_DAY` | sed -E 's/[0-9 ]{2}/\0| /g'
echo " |"

for lang in $LANGS; do
    printf "%-${LONGEST_LANG}s " $lang
    echo -n "| "
    for day in `seq 1 $MAX_DAY`; do
        (echo "$DAT" | grep "$day/$lang" >/dev/null) \
            && echo -n "X " \
            || echo -n "  "
    done | sed -E 's/[X ] /\0| /g'
    echo
done
