#!/bin/bash
# Collapse newlines \
  tr '\n' '\r' | sed -E 's/(\S)\r/\1 /g' | tr '\r' '\n' | \
# Filter passports w/ all fields (excl. cid) \
  grep -wE 'byr:(19[2-9][0-9]|200[0-2])' | \
  grep -wE 'iyr:(201[0-9]|2020)' | \
  grep -wE 'eyr:(202[0-9]|2030)' | \
  grep -wE 'hgt:((1[5-8][0-9]|19[0-3])cm|(59|6[0-9]|7[0-6])in)' | \
  grep -wE 'hcl:#[0-9a-f]{6}' | \
  grep -wE 'ecl:(amb|blu|brn|gry|grn|hzl|oth)' | \
  grep -wE 'pid:[0-9]{9}' | \
  sed -E 's/ $//g' | \
# Count matching passports \
  wc -l
