#!/usr/bin/env -S gawk -f
BEGIN {
    RS = "\n\n"
    FS = "[\n ]"
    COUNT = 0
}

NF >= 7                                                  && \
/\ybyr:(19[2-9][0-9]|200[0-2])\y/                        && \
/\yiyr:(201[0-9]|2020)\y/                                && \
/\yeyr:(202[0-9]|2030)\y/                                && \
/\yhgt:((1[5-8][0-9]|19[0-3])cm|(59|6[0-9]|7[0-6])in)\y/ && \
/\yecl:(amb|blu|brn|gry|grn|hzl|oth)\y/                  && \
/\yhcl:#[0-9a-f]{6}\y/                                   && \
/\ypid:[0-9]{9}\y/                                       && \
1 {
    COUNT += 1
}

END {
    print COUNT
}
